name: presentation_master_2
description: All-in-one presentation remote and note taking app

publish_to: 'none'

version: 3.0.1+47

environment:
  sdk: '>=2.19.2 <4.0.0'





dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0

  shared_preferences: ^2.1.1

  # TODO: Uncomment for android, comment to build iOS
  #wakelock_plus: ^1.1.1
  #flutter_vibrate: ^1.3.0

  http: ^1.1.0
  # TODO: Uncomment for android, comment to build iOS
  #network_info_plus: ^4.0.1
  #ping_discover_network_forked: ^0.0.1
  url_launcher: ^6.0.18

  # Uncomment to use, comment to build iOS
  #flutter_native_splash: ^2.2.0

  google_fonts: ^4.0.3
  flutter_markdown: ^0.6.10+2
  skeletons: ^0.0.3




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  rename: ^2.0.1





flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "launcher_icon.png"

flutter:
  uses-material-design: true




# Uncomment to use, comment to build iOS
#flutter_native_splash:

#  color: "#000000"
  #background_image: "assets/background.png"

  # Optional parameters are listed below.  To enable a parameter, uncomment the line by removing
  # the leading # character.

##  image: ./splash_screen_icon.png

  # https://developer.android.com/guide/topics/ui/splash-screen
#  android_12:
  
#    image: ./splash_screen_icon.png

#    color: "#000000"

    #icon_background_color: "#111111"