name: presenter_2
description: All-in-one presentation remote and note taking app, intuitive and customizable

publish_to: 'none'

version: 2.2.0+45

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  logger: ^1.1.0

  permission_handler: ^10.2.0
  package_info_plus: ^1.4.2
  path_provider: ^2.0.9 # iOS-C

  flutter_vibrate: ^1.3.0

  flutter_blue: ^0.8.0
  url_launcher: ^6.0.18
  share_plus: ^4.0.4

  animate_gradient: ^0.0.2    # TODO: R?
  snapping_sheet: ^3.1.0
  flutter_onboarding_slider: ^1.0.9

  material_design_icons_flutter: ^5.0.6996
  google_fonts: ^3.0.1
  flutter_markdown: ^0.6.10+2
  markdown_editor_plus: ^0.2.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  rename: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: play_store_512.png

flutter:
  uses-material-design: true
  #assets:
  #- [path]
